import "server-only";

import type { Category, Product, Size } from "@/lib/types";

/**
 * The Levenon catalogue — twelve real pieces from the Idraak/Daraz database.
 *
 * This module is the **storage layer** and the only place product rows are
 * defined. It is import-guarded with `server-only` so a stray client import
 * fails the build instead of shipping the catalogue to the browser.
 * `lib/server/products.ts` is the interface everything else calls, and it does
 * not change when this file does.
 *
 * ---------------------------------------------------------------------------
 * PROVENANCE — every field below traces to a row in `LevenonIdraak.sql`.
 *
 * `id` carries the ERP product id (`lv-1050` is `products.id = 1050`) so any
 * row here can be found in the source database in one query. Prices are
 * `products.recommended_price` converted to integer minor units. Fabric and
 * care lines come from `product_attributes`; descriptions are the shop's own
 * `main_description`, trimmed. Photography is joined through Spatie `media`
 * rows on the `cloudinary` disk — the client's own account, not a marketplace
 * CDN that could block hotlinking.
 *
 * **The twelve were chosen by eye, and that mattered.** Of 763 candidates with
 * three or more live images, a large share are marketplace listing collages
 * rather than photography: annotation labels burned into the pixels ("NECK",
 * "EMBROIDERED DAMAN"), flat-lays on artificial grass, and in places another
 * brand's watermark. Every image below was inspected; several products carry
 * fewer than three because their later frames were collages.
 *
 * Two fields are NOT trustworthy from the source and are marked at their use:
 * stock (`products.quantity` sits at the schema default of 10 on every row)
 * and size (the dump's only values are "Standard" and "Un-stitched" — these
 * are lengths of cloth, not garments in sizes).
 * ---------------------------------------------------------------------------
 */

const categories = {
  lawn: {
    id: "cat-lawn",
    slug: "lawn",
    name: "Lawn",
    tagline: "Airjet-woven, printed and embroidered",
    sortOrder: 1,
  },
  cotton: {
    id: "cat-cotton",
    slug: "cotton",
    name: "Cotton",
    tagline: "Chikankari and cross-stitch, by hand",
    sortOrder: 2,
  },
  chiffon: {
    id: "cat-chiffon",
    slug: "chiffon",
    name: "Chiffon",
    tagline: "Adda work over a weightless ground",
    sortOrder: 3,
  },
  silk: {
    id: "cat-silk",
    slug: "silk",
    name: "Silk",
    tagline: "Shamoz and digital print, full fall",
    sortOrder: 4,
  },
  organza: {
    id: "cat-organza",
    slug: "organza",
    name: "Organza",
    tagline: "Sheer, structured, sequence-set",
    sortOrder: 5,
  },
  net: {
    id: "cat-net",
    slug: "net",
    name: "Net",
    tagline: "Spengle and cutwork, formal weight",
    sortOrder: 6,
  },
} satisfies Record<string, Category>;

export const CATEGORIES: Category[] = Object.values(categories).sort(
  (a, b) => a.sortOrder - b.sortOrder,
);

export const SEASON = "Edit 01";

/**
 * Every piece is unstitched cloth, so there is exactly one variant and it has
 * no size. The dump agrees: across 156 variation attribute rows the only
 * values are "Standard" and "Un-stitched".
 *
 * `stockOnHand` is **set by hand, per product** — see the figure at each call
 * site. `products.quantity` in the source database is 10 on every single row,
 * which is the column's schema default and plainly was never edited; shipping
 * that would have been twelve identical fictions rather than one.
 *
 * The depths below follow how each piece is made. Machine-repeatable work
 * (print, schiffli, counted cross-stitch) runs deep and cheap. Hand labour
 * (chikankari, adda, spengle) is limited by karigar-hours, so it runs shallow
 * and dear. Two pieces are at zero, which is the state the waitlist exists for.
 *
 * These are still **estimates, not a stock feed.** When the ERP connection is
 * live, this function is where the real number arrives.
 */
function unstitched(
  productId: string,
  styleSku: string,
  stockOnHand: number,
): Product["variants"] {
  const size: Size = "Unstitched";
  return [
    {
      id: `${productId}-unstitched`,
      productId,
      size,
      sku: `${styleSku}-OS`,
      stockOnHand,
    },
  ];
}

export const PRODUCTS: Product[] = [
  {
    id: "lv-1050",
    slug: "scifflie-lawn-suit",
    sku: "LV-LW-1050",
    name: "Scifflie Lawn Suit",
    category: categories.lawn,
    priceMinor: 512300,
    currency: "PKR",
    blurb: "Lawn light enough to read a page through, carrying schiffli work dense enough to hold its own weight.",
    description: [
      "Lawn is a plain weave spun fine and set open — the cloth Punjab summers are built around. It takes a print flat, breathes through it, and creases the way cotton is supposed to.",
      "Front, back and sleeves are worked on a schiffli loom, a shuttle machine that lays continuous motif at a density hand-guided work cannot reach, then finished with attached beads and a run of lace along the daman. The trouser is dyed cambric — closer set than the shirt cloth, so the leg falls straight.",
      "Cut, it carries weight only where the embroidery sits. Everything between stays as light as it started.",
    ],
    specs: [
      { label: "Shirt", value: "Lawn" },
      { label: "Trouser", value: "Cambric" },
      { label: "Dupatta", value: "Silk" },
      { label: "Work", value: "Embroidered, Scifflie, Lace, Digital Print, Beats Attach" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-1050", "LV-LW-1050", 12), // schiffli is loom work, so repeatable
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1759313523/Products/1050/image/media_1759313455744_1759313523512.jpg", alt: "Scifflie Lawn Suit — Lawn", width: 871, height: 1125 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1759313524/Products/1050/image/media_1759313456258_1759313524571.jpg", alt: "Scifflie Lawn Suit, view 2", width: 1280, height: 904 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1759313526/Products/1050/image/media_1759313456626_1759313525937.jpg", alt: "Scifflie Lawn Suit, view 3", width: 1040, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-01T10:12:03.000Z",
    updatedAt: "2025-10-01T10:12:20.000Z",
  },
  {
    id: "lv-615",
    slug: "airjet-lawn-suit",
    sku: "LV-LW-615",
    name: "Airjet Lawn Suit",
    category: categories.lawn,
    priceMinor: 322000,
    currency: "PKR",
    blurb: "Pure 90/70 airjet lawn — crisp off the loom, cooler the longer the day runs.",
    description: [
      "90/70 is the count: ninety threads to the inch through the warp, seventy through the weft. Woven on an airjet loom, which throws the weft on a jet of air and returns a flat, even cloth without the slubbing a slower loom leaves behind.",
      "The shirt is printed rather than embroidered, with worked patches set at the neck and daman where print alone would stop short. Trouser is the same lawn, so shirt and leg move together; the dupatta is chiffon, lighter than both, so it reads as a separate layer instead of more of the same.",
      "This is the everyday end of the rail. Three pieces, one cloth, nothing that needs careful handling.",
    ],
    specs: [
      { label: "Shirt", value: "Lawn" },
      { label: "Trouser", value: "Lawn" },
      { label: "Dupatta", value: "Chiffon" },
      { label: "Work", value: "Print, Patch Work" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-615", "LV-LW-615", 0), // sold out — the cheapest lawn goes first
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756125699/Products/615/image/media_1756125498763_1756125698756.jpg", alt: "Airjet Lawn Suit — Lawn", width: 853, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756125699/Products/615/image/media_1756125499118_1756125699706.jpg", alt: "Airjet Lawn Suit, view 2", width: 853, height: 1280 },
    ],
    visual: "stitch",
    status: "active",
    createdAt: "2025-08-25T12:41:39.000Z",
    updatedAt: "2025-08-25T12:41:50.000Z",
  },
  {
    id: "lv-483",
    slug: "adda-work-chiffon",
    sku: "LV-CH-483",
    name: "Adda Work Chiffon Suit",
    category: categories.chiffon,
    priceMinor: 608800,
    currency: "PKR",
    blurb: "Crepe-twist chiffon, held flat on the frame while the neck and sleeves are worked by hook.",
    description: [
      "Chiffon is woven from yarns twisted hard in opposite directions. That twist is what gives it the faint grain under the hand and a drape that will not hold a fold. Sheer enough to need an inner, light enough that a full sleeve costs nothing in weight.",
      "Neck and sleeves are adda work — the cloth stretched drum-tight across a wooden frame while the karigar works from above with a hook. On a ground this fine it is the only way to set this much sequence without pulling the weave out of true. The daman carries a separate worked border; the trouser is satin, whose shine comes from the weave structure rather than a finish.",
      "Stitched, the weight sits at the hem and the neck and nowhere else, so the body of the shirt still moves.",
    ],
    specs: [
      { label: "Shirt", value: "Chiffon" },
      { label: "Trouser", value: "Satin" },
      { label: "Dupatta", value: "Chiffon" },
      { label: "Work", value: "Embroidered, Adda Work, Sequence" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-483", "LV-CH-483", 4), // adda work at neck and sleeve
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755956303/Products/483/image/media_1755956018371_1755956302811.jpg", alt: "Adda Work Chiffon Suit — Chiffon", width: 800, height: 1200 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755956303/Products/483/image/media_1755956018699_1755956303753.jpg", alt: "Adda Work Chiffon Suit, view 2", width: 797, height: 1062 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755956304/Products/483/image/media_1755956019031_1755956304342.jpg", alt: "Adda Work Chiffon Suit, view 3", width: 800, height: 1200 },
    ],
    visual: "knot",
    status: "active",
    createdAt: "2025-08-23T13:38:23.000Z",
    updatedAt: "2025-08-23T13:38:34.000Z",
  },
  {
    id: "lv-511",
    slug: "embroidered-chiffon",
    sku: "LV-CH-511",
    name: "Embroidered Chiffon Suit",
    category: categories.chiffon,
    priceMinor: 395600,
    currency: "PKR",
    blurb: "Chiffon with no memory of its own — it takes the shape the cut gives it and keeps none.",
    description: [
      "A plain-weave chiffon, opaque only where the thread sits. It holds no crease and returns to flat the moment it is put down.",
      "Front and back are both embroidered, which is less usual than it sounds — most suits leave the back plain and let the dupatta cover it. Daman and back borders are worked separately, and the dupatta is bordered on all four sides rather than two, so it reads finished whichever way it is thrown.",
      "Sleeves are cut long for a full fall. The trouser is silk, smooth enough that the shirt does not catch on it.",
    ],
    specs: [
      { label: "Shirt", value: "Chiffon" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Chiffon" },
      { label: "Work", value: "Embroidery" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-511", "LV-CH-511", 9), // machine embroidery, semi-formal
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755972528/Products/511/image/media_1755972504453_1755972526689.jpg", alt: "Embroidered Chiffon Suit — Chiffon", width: 904, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755972529/Products/511/image/media_1755972504925_1755972529242.jpg", alt: "Embroidered Chiffon Suit, view 2", width: 904, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755972530/Products/511/image/media_1755972505809_1755972530739.jpg", alt: "Embroidered Chiffon Suit, view 3", width: 904, height: 1280 },
    ],
    visual: "seam",
    status: "active",
    createdAt: "2025-08-23T18:08:47.000Z",
    updatedAt: "2025-08-23T18:09:00.000Z",
  },
  {
    id: "lv-648",
    slug: "monsoon-blooms",
    sku: "LV-CT-648",
    name: "Monsoon Blooms Chikankari",
    category: categories.cotton,
    priceMinor: 514800,
    currency: "PKR",
    blurb: "Chikankari worked by hand on soft cotton, under an organza dupatta that stands away from it.",
    description: [
      "Cotton, plain and opaque, chosen for what it does in humidity rather than how it photographs. The dupatta is organza — a sheer weave of tightly twisted filament that holds its own shape instead of falling against the body.",
      "Chikankari is needlework, not machine work: a family of stitches worked fine, some from the face and some from the reverse so the motif reads as shadow through the cloth. The neck patch is separate handwork. This is the Monsoon Blooms run.",
      "Tonal work on a pale ground hides nothing. Held up to a window, the back of the front panel is the honest view of it.",
    ],
    specs: [
      { label: "Shirt", value: "Cotton" },
      { label: "Trouser", value: "Cotton" },
      { label: "Dupatta", value: "Organza" },
      { label: "Work", value: "Chikankari Embroidery, Handwork Embroidery" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-648", "LV-CT-648", 3), // chikankari entirely by hand — the hard ceiling
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756313373/Products/648/image/media_1756313349406_1756313372888.jpg", alt: "Monsoon Blooms Chikankari — Cotton", width: 1080, height: 1080 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756313374/Products/648/image/media_1756313349956_1756313373732.jpg", alt: "Monsoon Blooms Chikankari, view 2", width: 1080, height: 1080 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756313374/Products/648/image/media_1756313350283_1756313374755.jpg", alt: "Monsoon Blooms Chikankari, view 3", width: 1080, height: 1080 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-08-27T16:49:33.000Z",
    updatedAt: "2025-08-27T16:49:53.000Z",
  },
  {
    id: "lv-1038",
    slug: "cross-stitch-cotton",
    sku: "LV-CT-1038",
    name: "Cross-Stitch Cotton Suit",
    category: categories.cotton,
    priceMinor: 334900,
    currency: "PKR",
    blurb: "Soft cotton in a black ground, with cross-stitch counted in colour across it.",
    description: [
      "A soft-finished cotton that takes dye deep rather than sitting it on the surface. Black is the least forgiving ground to embroider — every stitch set a thread out of line shows.",
      "Cross-stitch is counted work. Each stitch crosses the same two threads of the weave, so the motif is built square by square instead of drawn, and the repeat stays true across the panel. The dupatta is chiffon carrying the same motif at a lighter count; the trouser is plain lawn, left alone.",
      "The least formal thing in the edit, and the one most likely to be worn twice a week.",
    ],
    specs: [
      { label: "Shirt", value: "Cotton" },
      { label: "Trouser", value: "Lawn" },
      { label: "Dupatta", value: "Chiffon" },
      { label: "Work", value: "Embroidery" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-1038", "LV-CT-1038", 18), // counted machine stitch, everyday cloth
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1759061075/Products/1038/image/media_1759060673860_1759061074881.jpg", alt: "Cross-Stitch Cotton Suit — Cotton", width: 868, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1759061075/Products/1038/image/media_1759060674184_1759061075583.jpg", alt: "Cross-Stitch Cotton Suit, view 2", width: 990, height: 946 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1759061076/Products/1038/image/media_1759060674531_1759061076131.jpg", alt: "Cross-Stitch Cotton Suit, view 3", width: 990, height: 851 },
    ],
    visual: "stitch",
    status: "active",
    createdAt: "2025-09-28T12:04:35.000Z",
    updatedAt: "2025-09-28T12:04:45.000Z",
  },
  {
    id: "lv-532",
    slug: "spengle-net-suit",
    sku: "LV-NT-532",
    name: "Spengle Net Suit",
    category: categories.net,
    priceMinor: 649000,
    currency: "PKR",
    blurb: "Net has no drape of its own — it takes the shape of whatever is worked onto it.",
    description: [
      "Net is open mesh: structure and nothing else. Left plain it would hang like a curtain. Here the embroidery is what gives the cloth body, so the ground and the work are not separable.",
      "Spengle work runs through front, back and sleeves — sequin set in close fields with zari and stones laid through it. The dupatta border is cutwork on all four sides: the ground is cut away around the motif so the edge follows the embroidery instead of a straight hem.",
      "It comes with a shamoz silk inner as well as the trouser, because net against the skin is not a decision to leave until later.",
    ],
    specs: [
      { label: "Shirt", value: "Net" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Net" },
      { label: "Work", value: "Embroidered, Spengle Work, Zari, Stones, Cutwork" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-532", "LV-NT-532", 2), // heaviest work in the edit — nearly gone
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756034151/Products/532/image/media_1756033996480_1756034150611.jpg", alt: "Spengle Net Suit — Net", width: 853, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756034151/Products/532/image/media_1756033996791_1756034151448.jpg", alt: "Spengle Net Suit, view 2", width: 853, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756034152/Products/532/image/media_1756033997104_1756034152014.jpg", alt: "Spengle Net Suit, view 3", width: 853, height: 1280 },
    ],
    visual: "knot",
    status: "active",
    createdAt: "2025-08-24T11:15:51.000Z",
    updatedAt: "2025-08-24T11:16:14.000Z",
  },
  {
    id: "lv-1058",
    slug: "sequence-net-suit",
    sku: "LV-NT-1058",
    name: "Sequence Net Suit",
    category: categories.net,
    priceMinor: 608800,
    currency: "PKR",
    blurb: "Sequence set across net until the mesh closes, under flat digital print on silk.",
    description: [
      "The same open net, this time carrying sequence embroidery through front, back and sleeves at a density that shuts the ground. Held still it reads solid; moved, the mesh shows through again.",
      "The dupatta goes the other way — digital-printed silk, flat colour, edged on four sides with sequence-embroidered lace to tie it back to the shirt. Adda work at the neck.",
      "The trouser is plain malai, soft-faced and left undecorated. Everything on this suit is meant to happen above the waist.",
    ],
    specs: [
      { label: "Shirt", value: "Net" },
      { label: "Trouser", value: "Lawn" },
      { label: "Dupatta", value: "Silk" },
      { label: "Work", value: "Sequence Embroidery, Adda Work, Digital Print, Lace" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-1058", "LV-NT-1058", 6), // sequence at density
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1759313841/Products/1058/image/media_1759313468504_1759313841024.jpg", alt: "Sequence Net Suit — Net", width: 853, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1759313842/Products/1058/image/media_1759313468838_1759313842066.jpg", alt: "Sequence Net Suit, view 2", width: 854, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1759313842/Products/1058/image/media_1759313469173_1759313842721.jpg", alt: "Sequence Net Suit, view 3", width: 853, height: 1280 },
    ],
    visual: "seam",
    status: "active",
    createdAt: "2025-10-01T10:17:21.000Z",
    updatedAt: "2025-10-01T10:17:36.000Z",
  },
  {
    id: "lv-550",
    slug: "tussel-organza-suit",
    sku: "LV-OR-550",
    name: "Tussel Organza Suit",
    category: categories.organza,
    priceMinor: 568600,
    currency: "PKR",
    blurb: "Organza holds a shape rather than falling into one, which is why the tussels swing clear of it.",
    description: [
      "Organza is woven from hard-twisted filament and finished stiff. It stands off the body, keeps a crease, and shows every stitch on both faces — a cloth with no back to hide in.",
      "Front and back are embroidered through, the neck worked on the adda by hook. Hanging tussels run the front and back borders and, because the ground is rigid, they hang free instead of catching against it. The dupatta is finished with four-sided cutwork and kiran lace at the edge.",
      "The trouser is silk and deliberately quiet. The shirt is doing the work.",
    ],
    specs: [
      { label: "Shirt", value: "Organza" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Organza" },
      { label: "Work", value: "Embroidery, Adda Work, Hanging Tussels, Cut Work, Kiran Lace" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-550", "LV-OR-550", 5), // tussels hung by hand, four-sided cutwork
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756055014/Products/550/image/media_1756054963290_1756055014566.jpg", alt: "Tussel Organza Suit — Organza", width: 853, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756055015/Products/550/image/media_1756054963608_1756055015431.jpg", alt: "Tussel Organza Suit, view 2", width: 853, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756055016/Products/550/image/media_1756054963923_1756055015963.jpg", alt: "Tussel Organza Suit, view 3", width: 853, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-08-24T17:03:35.000Z",
    updatedAt: "2025-08-24T17:03:43.000Z",
  },
  {
    id: "lv-1044",
    slug: "festive-organza-suit",
    sku: "LV-OR-1044",
    name: "Festive Organza Suit",
    category: categories.organza,
    priceMinor: 506400,
    currency: "PKR",
    blurb: "Sequence and handwork across organza, with the back left plain as a rest for the eye.",
    description: [
      "Sheer organza again — crisp, slightly wiry, taking sequence on the front and heavy embroidery through the sleeves.",
      "The daman patches are worked separately and set on, handwork laid over the sequence and tussels hung from the edge. The back is left as a flat panel against everything happening at the front, and that restraint is the reason the suit does not read as noise.",
      "Cutwork through the sleeves, dyed malai trouser beneath. Organza creases. That is the cloth, not a fault in it.",
    ],
    specs: [
      { label: "Shirt", value: "Organza" },
      { label: "Trouser", value: "Lawn" },
      { label: "Dupatta", value: "Organza" },
      { label: "Work", value: "Embroidery, Sequence, Handwork, Cutwork, Hanging Tussles" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-1044", "LV-OR-1044", 0), // sold out — festive organza at its peak
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1759061267/Products/1044/image/media_1759060685129_1759061267264.jpg", alt: "Festive Organza Suit — Organza", width: 905, height: 1280 },
    ],
    visual: "stitch",
    status: "active",
    createdAt: "2025-09-28T12:07:47.000Z",
    updatedAt: "2025-09-28T12:08:03.000Z",
  },
  {
    id: "lv-508",
    slug: "handwork-silk-suit",
    sku: "LV-SK-508",
    name: "Handwork Silk Suit",
    category: categories.silk,
    priceMinor: 417000,
    currency: "PKR",
    blurb: "Digital print laid down flat first, then stone and handwork set on top of it.",
    description: [
      "Silk through all three pieces — shirt, trouser and dupatta cut from the same cloth, which is less common than it sounds and is what makes the suit read as one thing rather than three.",
      "The order is the point. Print goes on flat across front, back, sleeves, dupatta and trouser; the handwork and stones are set afterwards, following the printed motif instead of ignoring it. The gala carries the heaviest embroidery on the suit.",
      "Printed silk takes light differently from embroidered silk. Across a room this one changes with where you stand.",
    ],
    specs: [
      { label: "Shirt", value: "Silk" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Silk" },
      { label: "Work", value: "Embroidery, Stone Work, Hand Work, Digital Print" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-508", "LV-SK-508", 7), // handwork over print
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755957059/Products/508/image/media_1755956068165_1755957059300.jpg", alt: "Handwork Silk Suit — Silk", width: 889, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755957060/Products/508/image/media_1755956068476_1755957060092.jpg", alt: "Handwork Silk Suit, view 2", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755957060/Products/508/image/media_1755956068798_1755957060674.jpg", alt: "Handwork Silk Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "knot",
    status: "active",
    createdAt: "2025-08-23T13:50:59.000Z",
    updatedAt: "2025-08-23T13:51:07.000Z",
  },
  {
    id: "lv-937",
    slug: "shamoz-silk-suit",
    sku: "LV-SK-937",
    name: "Shamoz Silk Suit",
    category: categories.silk,
    priceMinor: 296200,
    currency: "PKR",
    blurb: "Shamoz silk — smooth-faced, mid-weight, matte rather than shining.",
    description: [
      "Shamoz silk sits heavier in the hand than chiffon and falls in long folds instead of small ones. The face is smooth and the lustre is low, so it reads as cloth rather than as surface.",
      "There is no embroidery anywhere on this suit. The pattern is digital print, carried across the shirt and matched onto the trouser so the two run continuous once stitched.",
      "The plainest thing in the edit, and the only one you could put on without thinking about it.",
    ],
    specs: [
      { label: "Shirt", value: "Silk" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Silk" },
      { label: "Work", value: "Digital Printed" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-937", "LV-SK-937", 21), // print only, no hand labour — deepest run
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1758747713/Products/937/image/media_1758747054325_1758747713030.jpg", alt: "Shamoz Silk Suit — Silk", width: 1025, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1758747714/Products/937/image/media_1758747054690_1758747714363.jpg", alt: "Shamoz Silk Suit, view 2", width: 1025, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1758747715/Products/937/image/media_1758747055073_1758747715245.jpg", alt: "Shamoz Silk Suit, view 3", width: 1032, height: 1280 },
    ],
    visual: "seam",
    status: "active",
    createdAt: "2025-09-24T21:01:53.000Z",
    updatedAt: "2025-09-24T21:02:06.000Z",
  },

  // ---------------------------------------------------------------------
  // Batch 2 — 36 more, 6 per category on top of the 2 above (8/category,
  // 48 total). Same source (`LevenonIdraak.sql`), same adapter pattern:
  // `recommended_price`/`base_price`/`sale_price` → priceMinor, Cloudinary
  // images HEAD-verified live with real dimensions read from each file's own
  // JPEG header (not guessed), stock estimated from the same hand-labour
  // logic as Batch 1 (chikankari/adda/handwork runs shallow, digital
  // print/schiffli runs deep).
  //
  // Copy here is template-generated from each row's own title — matched
  // work-technique and dupatta-fabric keywords slotted into a fixed
  // paragraph shape — not individually hand-written the way the original 12
  // were. It is honest about what it's describing (nothing invented beyond
  // what the source title states) but reads more uniform across 36 pieces
  // than the original dozen's bespoke copy; some names still repeat within
  // a category where the source titles themselves were generic marketplace
  // listings with nothing distinguishing to key off. A handful of first-pick
  // candidates were rejected after actually looking at their photography —
  // burned-in annotation labels, grass-background flat-lays, or another
  // brand's watermark (MARIA.B, BAROQUE, ASIM JOFA, IZNIK, a phone-brand
  // corner logo) — and swapped for a clean alternate from the same product's
  // other listing photos, or a different product entirely.
  // ---------------------------------------------------------------------
  {
    id: "lv-15",
    slug: "digital-printed-embroidered-lawn-suit-lawn",
    sku: "LV-LW-15",
    name: "Digital Printed Embroidered Lawn Suit",
    category: categories.lawn,
    priceMinor: 464800,
    currency: "PKR",
    blurb: "Lawn carrying a digital print laid down before anything else, under a chiffon dupatta.",
    description: [
      "Lawn is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is a digital print laid down before anything else, with embroidery carried across the front and daman.",
      "The dupatta is chiffon, set apart from the shirt cloth on purpose — a lighter hand than the suit itself, so it reads as a separate layer rather than more of the same.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Lawn" },
      { label: "Trouser", value: "Cambric" },
      { label: "Dupatta", value: "Chiffon" },
      { label: "Work", value: "Digital Print, Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-15", "LV-LW-15", 12),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752592430/Products/20/image/media_1752592356502_1752592430127.jpg", alt: "Digital Printed Embroidered Lawn Suit", width: 920, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752592431/Products/20/image/media_1752592356835_1752592431266.jpg", alt: "Digital Printed Embroidered Lawn Suit, view 2", width: 1133, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752592432/Products/20/image/media_1752592357140_1752592432234.jpg", alt: "Digital Printed Embroidered Lawn Suit, view 3", width: 920, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-9",
    slug: "embroidered-lawn-suit-lawn",
    sku: "LV-LW-9",
    name: "Embroidered Lawn Suit",
    category: categories.lawn,
    priceMinor: 550600,
    currency: "PKR",
    blurb: "Lawn carrying embroidery carried across the front and daman.",
    description: [
      "Lawn is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Lawn" },
      { label: "Trouser", value: "Cambric" },
      { label: "Dupatta", value: "Lawn" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-9", "LV-LW-9", 14),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752590541/Products/14/image/media_1752590512948_1752590540973.jpg", alt: "Embroidered Lawn Suit", width: 645, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752590539/Products/14/image/media_1752590512341_1752590539128.jpg", alt: "Embroidered Lawn Suit, view 2", width: 990, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752590540/Products/14/image/media_1752590512648_1752590540165.jpg", alt: "Embroidered Lawn Suit, view 3", width: 958, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-30",
    slug: "heavy-embroidered-lawn-suit-lawn",
    sku: "LV-LW-30",
    name: "Heavy Embroidered Lawn Suit",
    category: categories.lawn,
    priceMinor: 700700,
    currency: "PKR",
    blurb: "Lawn carrying embroidery carried across the front and daman, under a chiffon dupatta.",
    description: [
      "Lawn is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "The dupatta is chiffon, set apart from the shirt cloth on purpose — a lighter hand than the suit itself, so it reads as a separate layer rather than more of the same.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Lawn" },
      { label: "Trouser", value: "Cambric" },
      { label: "Dupatta", value: "Chiffon" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-30", "LV-LW-30", 6),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604569/Products/35/image/media_1752604442296_1752604568833.jpg", alt: "Heavy Embroidered Lawn Suit", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604568/Products/35/image/media_1752604441925_1752604567942.jpg", alt: "Heavy Embroidered Lawn Suit, view 2", width: 699, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604569/Products/35/image/media_1752604442641_1752604569547.jpg", alt: "Heavy Embroidered Lawn Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-34",
    slug: "digital-printed-lawn-suit-lawn",
    sku: "LV-LW-34",
    name: "Digital Printed Lawn Suit",
    category: categories.lawn,
    priceMinor: 328900,
    currency: "PKR",
    blurb: "Lawn carrying a digital print laid down before anything else.",
    description: [
      "Lawn is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is a digital print laid down before anything else.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Lawn" },
      { label: "Trouser", value: "Cambric" },
      { label: "Dupatta", value: "Lawn" },
      { label: "Work", value: "Digital Print" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-34", "LV-LW-34", 24),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604671/Products/39/image/media_1752604447717_1752604669286.jpg", alt: "Digital Printed Lawn Suit", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604672/Products/39/image/media_1752604448204_1752604672284.jpg", alt: "Digital Printed Lawn Suit, view 2", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604673/Products/39/image/media_1752604448574_1752604673031.jpg", alt: "Digital Printed Lawn Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-46",
    slug: "digital-printed-lawn-suit-lawn-46",
    sku: "LV-LW-46",
    name: "Digital Printed Lawn Suit",
    category: categories.lawn,
    priceMinor: 264600,
    currency: "PKR",
    blurb: "Lawn carrying a digital print laid down before anything else.",
    description: [
      "Lawn is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is a digital print laid down before anything else.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Lawn" },
      { label: "Trouser", value: "Cambric" },
      { label: "Dupatta", value: "Lawn" },
      { label: "Work", value: "Digital Print" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-46", "LV-LW-46", 15),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752612541/Products/51/image/media_1752612512235_1752612540871.jpg", alt: "Digital Printed Lawn Suit", width: 1006, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752612542/Products/51/image/media_1752612512555_1752612541831.jpg", alt: "Digital Printed Lawn Suit, view 2", width: 838, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752612542/Products/51/image/media_1752612512881_1752612542475.jpg", alt: "Digital Printed Lawn Suit, view 3", width: 838, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-97",
    slug: "digital-printed-embroidered-lawn-suit-lawn-97",
    sku: "LV-LW-97",
    name: "Digital Printed Embroidered Lawn Suit",
    category: categories.lawn,
    priceMinor: 543400,
    currency: "PKR",
    blurb: "Lawn carrying a digital print laid down before anything else.",
    description: [
      "Lawn is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is a digital print laid down before anything else, with embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Lawn" },
      { label: "Trouser", value: "Cambric" },
      { label: "Dupatta", value: "Lawn" },
      { label: "Work", value: "Digital Print, Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-97", "LV-LW-97", 18),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752661340/Products/102/image/media_1752660678439_1752661340313.jpg", alt: "Digital Printed Embroidered Lawn Suit", width: 638, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752661341/Products/102/image/media_1752660678753_1752661341217.jpg", alt: "Digital Printed Embroidered Lawn Suit, view 2", width: 768, height: 1024 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752661342/Products/102/image/media_1752660679068_1752661341800.jpg", alt: "Digital Printed Embroidered Lawn Suit, view 3", width: 768, height: 1024 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-179",
    slug: "embroidered-cotton-suit-cotton",
    sku: "LV-CT-179",
    name: "Embroidered Cotton Suit",
    category: categories.cotton,
    priceMinor: 421900,
    currency: "PKR",
    blurb: "Cotton carrying chikankari worked by hand across the front, under a chiffon dupatta.",
    description: [
      "Cotton is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is chikankari worked by hand across the front, with embroidery carried across the front and daman.",
      "The dupatta is chiffon, set apart from the shirt cloth on purpose — a lighter hand than the suit itself, so it reads as a separate layer rather than more of the same.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Cotton" },
      { label: "Trouser", value: "Cambric" },
      { label: "Dupatta", value: "Chiffon" },
      { label: "Work", value: "Chikankari, Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-179", "LV-CT-179", 4),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752750038/Products/184/image/media_1752749691217_1752750037609.jpg", alt: "Embroidered Cotton Suit", width: 905, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752750039/Products/184/image/media_1752749691681_1752750038680.jpg", alt: "Embroidered Cotton Suit, view 2", width: 996, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752750039/Products/184/image/media_1752749692110_1752750039471.jpg", alt: "Embroidered Cotton Suit, view 3", width: 1033, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-28",
    slug: "embroidered-cotton-suit-with-net-dupatta-cotton",
    sku: "LV-CT-28",
    name: "Embroidered Cotton Suit with Net Dupatta",
    category: categories.cotton,
    priceMinor: 536300,
    currency: "PKR",
    blurb: "Cotton carrying embroidery carried across the front and daman, under a net dupatta.",
    description: [
      "Cotton is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "The dupatta is net, set apart from the shirt cloth on purpose — a lighter hand than the suit itself, so it reads as a separate layer rather than more of the same.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Cotton" },
      { label: "Trouser", value: "Cambric" },
      { label: "Dupatta", value: "Net" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-28", "LV-CT-28", 12),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604530/Products/33/image/media_1752604440249_1752604530478.jpg", alt: "Embroidered Cotton Suit with Net Dupatta", width: 659, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604530/Products/33/image/media_1752604439906_1752604529599.jpg", alt: "Embroidered Cotton Suit with Net Dupatta, view 2", width: 583, height: 800 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604531/Products/33/image/media_1752604440581_1752604531283.jpg", alt: "Embroidered Cotton Suit with Net Dupatta, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-166",
    slug: "rouge-khaadi-cotton-suit-cotton",
    sku: "LV-CT-166",
    name: "Rouge Khaadi Cotton Suit",
    category: categories.cotton,
    priceMinor: 700700,
    currency: "PKR",
    blurb: "Cotton carrying embroidery carried across the front and daman, under a khaadi net dupatta.",
    description: [
      "Cotton is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman, with a khaadi weave, drier and more textured than plain lawn.",
      "The dupatta is khaadi net, set apart from the shirt cloth on purpose — a lighter hand than the suit itself, so it reads as a separate layer rather than more of the same.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Cotton" },
      { label: "Trouser", value: "Cambric" },
      { label: "Dupatta", value: "Khaadi net" },
      { label: "Work", value: "Embroidered, Khaadi" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-166", "LV-CT-166", 8),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752749692/Products/171/image/media_1752749670679_1752749692649.jpg", alt: "Rouge Khaadi Cotton Suit", width: 658, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752749692/Products/171/image/media_1752749670355_1752749691592.jpg", alt: "Rouge Khaadi Cotton Suit, view 2", width: 720, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-324",
    slug: "digital-printed-embroidered-cotton-suit-cotton",
    sku: "LV-CT-324",
    name: "Digital Printed Embroidered Cotton Suit",
    category: categories.cotton,
    priceMinor: 502300,
    currency: "PKR",
    blurb: "Cotton carrying a digital print laid down before anything else.",
    description: [
      "Cotton is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is a digital print laid down before anything else, with embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Cotton" },
      { label: "Trouser", value: "Cambric" },
      { label: "Dupatta", value: "Cotton" },
      { label: "Work", value: "Digital Print, Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-324", "LV-CT-324", 24),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755517570/Products/324/image/media_1755517551955_1755517570235.jpg", alt: "Digital Printed Embroidered Cotton Suit", width: 659, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755517571/Products/324/image/media_1755517552401_1755517571359.jpg", alt: "Digital Printed Embroidered Cotton Suit, view 2", width: 599, height: 800 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755517572/Products/324/image/media_1755517552717_1755517571985.jpg", alt: "Digital Printed Embroidered Cotton Suit, view 3", width: 720, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-803",
    slug: "chikankari-digital-print-cotton-suit-cotton",
    sku: "LV-CT-803",
    name: "Chikankari Digital Print Cotton Suit",
    category: categories.cotton,
    priceMinor: 533700,
    currency: "PKR",
    blurb: "Cotton carrying chikankari worked by hand across the front.",
    description: [
      "Cotton is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is chikankari worked by hand across the front, a digital print laid down before anything else, and embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Cotton" },
      { label: "Trouser", value: "Cambric" },
      { label: "Dupatta", value: "Cotton" },
      { label: "Work", value: "Chikankari, Digital Print, Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-803", "LV-CT-803", 4),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1757001475/Products/803/image/media_1757000609047_1757001474719.jpg", alt: "Chikankari Digital Print Cotton Suit", width: 699, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1757001475/Products/803/image/media_1757000609394_1757001475708.jpg", alt: "Chikankari Digital Print Cotton Suit, view 2", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1757001476/Products/803/image/media_1757000609734_1757001476324.jpg", alt: "Chikankari Digital Print Cotton Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-862",
    slug: "festive-embroidered-cotton-suit-cotton",
    sku: "LV-CT-862",
    name: "Festive Embroidered Cotton Suit",
    category: categories.cotton,
    priceMinor: 548100,
    currency: "PKR",
    blurb: "Cotton carrying embroidery carried across the front and daman.",
    description: [
      "Cotton is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Cotton" },
      { label: "Trouser", value: "Cambric" },
      { label: "Dupatta", value: "Cotton" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-862", "LV-CT-862", 10),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1757541167/Products/862/image/media_1757541114120_1757541167176.jpg", alt: "Festive Embroidered Cotton Suit", width: 891, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1757541168/Products/862/image/media_1757541114445_1757541167927.jpg", alt: "Festive Embroidered Cotton Suit, view 2", width: 1124, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1757541168/Products/862/image/media_1757541114768_1757541168580.jpg", alt: "Festive Embroidered Cotton Suit, view 3", width: 893, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-39",
    slug: "embroidered-chiffon-suit-chiffon",
    sku: "LV-CH-39",
    name: "Embroidered Chiffon Suit",
    category: categories.chiffon,
    priceMinor: 800800,
    currency: "PKR",
    blurb: "Chiffon carrying embroidery carried across the front and daman.",
    description: [
      "Chiffon is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman, with the heavier hand of formalwear rather than an everyday cut.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Chiffon" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Chiffon" },
      { label: "Work", value: "Embroidered, Formal" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-39", "LV-CH-39", 10),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604799/Products/44/image/media_1752604455105_1752604798536.jpg", alt: "Embroidered Chiffon Suit", width: 1119, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604799/Products/44/image/media_1752604455481_1752604799571.jpg", alt: "Embroidered Chiffon Suit, view 2", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604800/Products/44/image/media_1752604455837_1752604800317.jpg", alt: "Embroidered Chiffon Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-75",
    slug: "embroidered-chiffon-suit-chiffon-75",
    sku: "LV-CH-75",
    name: "Embroidered Chiffon Suit",
    category: categories.chiffon,
    priceMinor: 550600,
    currency: "PKR",
    blurb: "Chiffon carrying embroidery carried across the front and daman.",
    description: [
      "Chiffon is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Chiffon" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Chiffon" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-75", "LV-CH-75", 6),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752660744/Products/80/image/media_1752660636175_1752660742269.jpg", alt: "Embroidered Chiffon Suit", width: 736, height: 1104 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752660745/Products/80/image/media_1752660636497_1752660745142.jpg", alt: "Embroidered Chiffon Suit, view 2", width: 800, height: 1160 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752660746/Products/80/image/media_1752660636796_1752660746032.jpg", alt: "Embroidered Chiffon Suit, view 3", width: 534, height: 800 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-125",
    slug: "heavy-embroidered-chiffon-suit-chiffon",
    sku: "LV-CH-125",
    name: "Heavy Embroidered Chiffon Suit",
    category: categories.chiffon,
    priceMinor: 514800,
    currency: "PKR",
    blurb: "Chiffon carrying embroidery carried across the front and daman.",
    description: [
      "Chiffon is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Chiffon" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Chiffon" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-125", "LV-CH-125", 6),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663568/Products/130/image/media_1752663273992_1752663565893.jpg", alt: "Heavy Embroidered Chiffon Suit", width: 608, height: 800 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663569/Products/130/image/media_1752663274313_1752663568721.jpg", alt: "Heavy Embroidered Chiffon Suit, view 2", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663569/Products/130/image/media_1752663274615_1752663569494.jpg", alt: "Heavy Embroidered Chiffon Suit, view 3", width: 736, height: 1067 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-17",
    slug: "phulkari-chiffon-suit-chiffon",
    sku: "LV-CH-17",
    name: "Phulkari Chiffon Suit",
    category: categories.chiffon,
    priceMinor: 464800,
    currency: "PKR",
    blurb: "Chiffon carrying embroidery worked across the front.",
    description: [
      "Chiffon is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery worked across the front.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Chiffon" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Chiffon" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-17", "LV-CH-17", 10),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752592475/Products/22/image/media_1752592358086_1752592474868.jpg", alt: "Phulkari Chiffon Suit", width: 1080, height: 1044 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752592476/Products/22/image/media_1752592358415_1752592476039.jpg", alt: "Phulkari Chiffon Suit, view 2", width: 1280, height: 1261 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752592476/Products/22/image/media_1752592358740_1752592476734.jpg", alt: "Phulkari Chiffon Suit, view 3", width: 1271, height: 1256 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-38",
    slug: "sequence-embroidered-chiffon-suit-chiffon",
    sku: "LV-CH-38",
    name: "Sequence Embroidered Chiffon Suit",
    category: categories.chiffon,
    priceMinor: 572000,
    currency: "PKR",
    blurb: "Chiffon carrying sequence set close enough to catch light at any angle.",
    description: [
      "Chiffon is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is sequence set close enough to catch light at any angle, embroidery carried across the front and daman, and handwork a machine cannot repeat at this density.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Chiffon" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Chiffon" },
      { label: "Work", value: "Sequence, Embroidered, Handwork" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-38", "LV-CH-38", 4),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604771/Products/43/image/media_1752604454465_1752604771186.jpg", alt: "Sequence Embroidered Chiffon Suit", width: 657, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604769/Products/43/image/media_1752604453820_1752604769211.jpg", alt: "Sequence Embroidered Chiffon Suit, view 2", width: 1022, height: 1160 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752604770/Products/43/image/media_1752604454150_1752604770447.jpg", alt: "Sequence Embroidered Chiffon Suit, view 3", width: 1027, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-232",
    slug: "sequence-embroidered-chiffon-suit-chiffon-232",
    sku: "LV-CH-232",
    name: "Sequence Embroidered Chiffon Suit",
    category: categories.chiffon,
    priceMinor: 829400,
    currency: "PKR",
    blurb: "Chiffon carrying sequence set close enough to catch light at any angle.",
    description: [
      "Chiffon is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is sequence set close enough to catch light at any angle, with embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Chiffon" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Chiffon" },
      { label: "Work", value: "Sequence, Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-232", "LV-CH-232", 6),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752753298/Products/237/image/media_1752753251630_1752753297722.jpg", alt: "Sequence Embroidered Chiffon Suit", width: 961, height: 1109 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752753299/Products/237/image/media_1752753251971_1752753298807.jpg", alt: "Sequence Embroidered Chiffon Suit, view 2", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752753299/Products/237/image/media_1752753252334_1752753299427.jpg", alt: "Sequence Embroidered Chiffon Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-19",
    slug: "adda-embroidered-silk-suit-silk",
    sku: "LV-SK-19",
    name: "Adda Embroidered Silk Suit",
    category: categories.silk,
    priceMinor: 536300,
    currency: "PKR",
    blurb: "Silk carrying adda work at the neck and sleeve.",
    description: [
      "Silk is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is adda work at the neck and sleeve, with embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Silk" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Silk" },
      { label: "Work", value: "Adda Work, Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-19", "LV-SK-19", 4),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752599671/Products/24/image/media_1752599646309_1752599671490.jpg", alt: "Adda Embroidered Silk Suit", width: 649, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752599672/Products/24/image/media_1752599646767_1752599672460.jpg", alt: "Adda Embroidered Silk Suit, view 2", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752599673/Products/24/image/media_1752599647114_1752599673379.jpg", alt: "Adda Embroidered Silk Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-119",
    slug: "embroidered-silk-suit-silk",
    sku: "LV-SK-119",
    name: "Embroidered Silk Suit",
    category: categories.silk,
    priceMinor: 507700,
    currency: "PKR",
    blurb: "Silk carrying embroidery carried across the front and daman, under a net dupatta.",
    description: [
      "Silk is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "The dupatta is net, set apart from the shirt cloth on purpose — a lighter hand than the suit itself, so it reads as a separate layer rather than more of the same.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Silk" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Net" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-119", "LV-SK-119", 14),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663416/Products/124/image/media_1752663261626_1752663415719.jpg", alt: "Embroidered Silk Suit", width: 652, height: 800 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663416/Products/124/image/media_1752663261938_1752663416603.jpg", alt: "Embroidered Silk Suit, view 2", width: 644, height: 800 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663417/Products/124/image/media_1752663262349_1752663417144.jpg", alt: "Embroidered Silk Suit, view 3", width: 672, height: 800 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-292",
    slug: "digital-printed-silk-suit-silk",
    sku: "LV-SK-292",
    name: "Digital Printed Silk Suit",
    category: categories.silk,
    priceMinor: 283900,
    currency: "PKR",
    blurb: "Silk carrying a digital print laid down before anything else.",
    description: [
      "Silk is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is a digital print laid down before anything else.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Silk" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Silk" },
      { label: "Work", value: "Digital Print" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-292", "LV-SK-292", 18),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755389004/Products/292/image/media_1755388983678_1755389004323.jpg", alt: "Digital Printed Silk Suit", width: 1172, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755389003/Products/292/image/media_1755388983341_1755389003385.jpg", alt: "Digital Printed Silk Suit, view 2", width: 1007, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755389005/Products/292/image/media_1755388983990_1755389004968.jpg", alt: "Digital Printed Silk Suit, view 3", width: 600, height: 600 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-468",
    slug: "embroidered-printed-silk-suit-silk",
    sku: "LV-SK-468",
    name: "Embroidered Printed Silk Suit",
    category: categories.silk,
    priceMinor: 460900,
    currency: "PKR",
    blurb: "Silk carrying embroidery carried across the front and daman.",
    description: [
      "Silk is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Silk" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Silk" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-468", "LV-SK-468", 12),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755861558/Products/468/image/media_1755861102248_1755861558193.jpg", alt: "Embroidered Printed Silk Suit", width: 904, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755861559/Products/468/image/media_1755861102561_1755861559180.jpg", alt: "Embroidered Printed Silk Suit, view 2", width: 904, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755861560/Products/468/image/media_1755861102884_1755861559858.jpg", alt: "Embroidered Printed Silk Suit, view 3", width: 904, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-621",
    slug: "digital-printed-silk-suit-silk-621",
    sku: "LV-SK-621",
    name: "Digital Printed Silk Suit",
    category: categories.silk,
    priceMinor: 296200,
    currency: "PKR",
    blurb: "Silk carrying a digital print laid down before anything else.",
    description: [
      "Silk is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is a digital print laid down before anything else.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Silk" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Silk" },
      { label: "Work", value: "Digital Print" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-621", "LV-SK-621", 15),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756137248/Products/621/image/media_1756137225401_1756137248278.jpg", alt: "Digital Printed Silk Suit", width: 854, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756137249/Products/621/image/media_1756137225855_1756137249279.jpg", alt: "Digital Printed Silk Suit, view 2", width: 1149, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756137251/Products/621/image/media_1756137226171_1756137250836.jpg", alt: "Digital Printed Silk Suit, view 3", width: 739, height: 979 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-623",
    slug: "digital-printed-silk-suit-silk-623",
    sku: "LV-SK-623",
    name: "Digital Printed Silk Suit",
    category: categories.silk,
    priceMinor: 296200,
    currency: "PKR",
    blurb: "Silk carrying a digital print laid down before anything else.",
    description: [
      "Silk is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is a digital print laid down before anything else.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Silk" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Silk" },
      { label: "Work", value: "Digital Print" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-623", "LV-SK-623", 21),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756137302/Products/623/image/media_1756137228347_1756137302223.jpg", alt: "Digital Printed Silk Suit", width: 853, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756137303/Products/623/image/media_1756137228663_1756137303398.jpg", alt: "Digital Printed Silk Suit, view 2", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1756137304/Products/623/image/media_1756137228976_1756137304224.jpg", alt: "Digital Printed Silk Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-104",
    slug: "digital-print-embroidered-organza-suit-organza",
    sku: "LV-OR-104",
    name: "Digital Print Embroidered Organza Suit",
    category: categories.organza,
    priceMinor: 443300,
    currency: "PKR",
    blurb: "Organza carrying a digital print laid down before anything else.",
    description: [
      "Organza is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is a digital print laid down before anything else, with embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Organza" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Organza" },
      { label: "Work", value: "Digital Print, Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-104", "LV-OR-104", 24),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752661519/Products/109/image/media_1752660690697_1752661519087.jpg", alt: "Digital Print Embroidered Organza Suit", width: 800, height: 1200 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752661520/Products/109/image/media_1752660691028_1752661520189.jpg", alt: "Digital Print Embroidered Organza Suit, view 2", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752661521/Products/109/image/media_1752660691362_1752661520955.jpg", alt: "Digital Print Embroidered Organza Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-96",
    slug: "embroidered-organza-suit-organza",
    sku: "LV-OR-96",
    name: "Embroidered Organza Suit",
    category: categories.organza,
    priceMinor: 514800,
    currency: "PKR",
    blurb: "Organza carrying embroidery carried across the front and daman.",
    description: [
      "Organza is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Organza" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Organza" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-96", "LV-OR-96", 8),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752661315/Products/101/image/media_1752660676543_1752661315574.jpg", alt: "Embroidered Organza Suit", width: 905, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752661315/Products/101/image/media_1752660676175_1752661314513.jpg", alt: "Embroidered Organza Suit, view 2", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752661316/Products/101/image/media_1752660676901_1752661316174.jpg", alt: "Embroidered Organza Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-154",
    slug: "embroidered-organza-suit-organza-154",
    sku: "LV-OR-154",
    name: "Embroidered Organza Suit",
    category: categories.organza,
    priceMinor: 486200,
    currency: "PKR",
    blurb: "Organza carrying embroidery carried across the front and daman.",
    description: [
      "Organza is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Organza" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Organza" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-154", "LV-OR-154", 14),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752745761/Products/159/image/media_1752745623105_1752745761166.jpg", alt: "Embroidered Organza Suit", width: 730, height: 1025 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752745762/Products/159/image/media_1752745623422_1752745762068.jpg", alt: "Embroidered Organza Suit, view 2", width: 732, height: 1021 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752745762/Products/159/image/media_1752745623748_1752745762657.jpg", alt: "Embroidered Organza Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-302",
    slug: "embroidered-organza-suit-organza-302",
    sku: "LV-OR-302",
    name: "Embroidered Organza Suit",
    category: categories.organza,
    priceMinor: 499700,
    currency: "PKR",
    blurb: "Organza carrying embroidery carried across the front and daman.",
    description: [
      "Organza is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman, with handwork a machine cannot repeat at this density.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Organza" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Organza" },
      { label: "Work", value: "Embroidered, Handwork" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-302", "LV-OR-302", 3),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755442537/Products/302/image/media_1755442450747_1755442536650.jpg", alt: "Embroidered Organza Suit", width: 736, height: 1024 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755442537/Products/302/image/media_1755442451081_1755442537695.jpg", alt: "Embroidered Organza Suit, view 2", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755442538/Products/302/image/media_1755442451403_1755442538415.jpg", alt: "Embroidered Organza Suit, view 3", width: 652, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-344",
    slug: "embroidered-organza-suit-organza-344",
    sku: "LV-OR-344",
    name: "Embroidered Organza Suit",
    category: categories.organza,
    priceMinor: 407300,
    currency: "PKR",
    blurb: "Organza carrying embroidery carried across the front and daman.",
    description: [
      "Organza is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Organza" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Organza" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-344", "LV-OR-344", 14),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755605997/Products/344/image/media_1755605836211_1755605997178.jpg", alt: "Embroidered Organza Suit", width: 854, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755605998/Products/344/image/media_1755605836592_1755605997865.jpg", alt: "Embroidered Organza Suit, view 2", width: 854, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1755605998/Products/344/image/media_1755605836986_1755605998422.jpg", alt: "Embroidered Organza Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-114",
    slug: "embroidered-zari-organza-suit-organza",
    sku: "LV-OR-114",
    name: "Embroidered Zari Organza Suit",
    category: categories.organza,
    priceMinor: 257400,
    currency: "PKR",
    blurb: "Organza carrying embroidery carried across the front and daman, under a organza dupatta.",
    description: [
      "Organza is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "The dupatta is organza, set apart from the shirt cloth on purpose — a lighter hand than the suit itself, so it reads as a separate layer rather than more of the same.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Organza" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Organza" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-114", "LV-OR-114", 14),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663302/Products/119/image/media_1752663253068_1752663302044.jpg", alt: "Embroidered Zari Organza Suit", width: 992, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663302/Products/119/image/media_1752663253432_1752663302845.jpg", alt: "Embroidered Zari Organza Suit, view 2", width: 995, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663303/Products/119/image/media_1752663253745_1752663303423.jpg", alt: "Embroidered Zari Organza Suit, view 3", width: 853, height: 1101 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-64",
    slug: "embroidered-net-suit-net",
    sku: "LV-NT-64",
    name: "Embroidered Net Suit",
    category: categories.net,
    priceMinor: 750800,
    currency: "PKR",
    blurb: "Net carrying embroidery carried across the front and daman, under a net dupatta.",
    description: [
      "Net is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman, with the heavier hand of formalwear rather than an everyday cut.",
      "The dupatta is net, set apart from the shirt cloth on purpose — a lighter hand than the suit itself, so it reads as a separate layer rather than more of the same.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Net" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Net" },
      { label: "Work", value: "Embroidered, Formal" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-64", "LV-NT-64", 10),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752614818/Products/69/image/media_1752614402674_1752614817740.jpg", alt: "Embroidered Net Suit", width: 711, height: 904 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752614818/Products/69/image/media_1752614402992_1752614818542.jpg", alt: "Embroidered Net Suit, view 2", width: 914, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752614819/Products/69/image/media_1752614403328_1752614819154.jpg", alt: "Embroidered Net Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-87",
    slug: "bridal-embroidered-net-suit-net",
    sku: "LV-NT-87",
    name: "Bridal Embroidered Net Suit",
    category: categories.net,
    priceMinor: 514800,
    currency: "PKR",
    blurb: "Net carrying embroidery carried across the front and daman.",
    description: [
      "Net is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman, with the heavier hand of formalwear rather than an everyday cut.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Net" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Net" },
      { label: "Work", value: "Embroidered, Formal" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-87", "LV-NT-87", 6),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752661059/Products/92/image/media_1752660660975_1752661058659.jpg", alt: "Bridal Embroidered Net Suit", width: 643, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752661059/Products/92/image/media_1752660661316_1752661059669.jpg", alt: "Bridal Embroidered Net Suit, view 2", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752661060/Products/92/image/media_1752660661650_1752661060328.jpg", alt: "Bridal Embroidered Net Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-123",
    slug: "embroidered-net-suit-net-123",
    sku: "LV-NT-123",
    name: "Embroidered Net Suit",
    category: categories.net,
    priceMinor: 421900,
    currency: "PKR",
    blurb: "Net carrying embroidery carried across the front and daman.",
    description: [
      "Net is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Net" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Net" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-123", "LV-NT-123", 12),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663509/Products/128/image/media_1752663270351_1752663508847.jpg", alt: "Embroidered Net Suit", width: 832, height: 1024 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663510/Products/128/image/media_1752663270670_1752663509999.jpg", alt: "Embroidered Net Suit, view 2", width: 768, height: 1024 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663510/Products/128/image/media_1752663270986_1752663510671.jpg", alt: "Embroidered Net Suit, view 3", width: 664, height: 1024 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-11",
    slug: "sequence-heavy-embroidered-net-suit-net",
    sku: "LV-NT-11",
    name: "Sequence Heavy Embroidered Net Suit",
    category: categories.net,
    priceMinor: 564900,
    currency: "PKR",
    blurb: "Net carrying sequence set close enough to catch light at any angle.",
    description: [
      "Net is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is sequence set close enough to catch light at any angle, embroidery carried across the front and daman, handwork a machine cannot repeat at this density, and the heavier hand of formalwear rather than an everyday cut.",
      "Front, back and sleeve are worked to the same density, so the piece reads consistently from any angle rather than carrying all its weight on one panel.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Net" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Net" },
      { label: "Work", value: "Sequence, Embroidered, Handwork, Formal" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-11", "LV-NT-11", 2),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752590591/Products/16/image/media_1752590514783_1752590591851.jpg", alt: "Sequence Heavy Embroidered Net Suit", width: 1158, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752590590/Products/16/image/media_1752590514172_1752590589973.jpg", alt: "Sequence Heavy Embroidered Net Suit, view 2", width: 960, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752590591/Products/16/image/media_1752590514481_1752590591142.jpg", alt: "Sequence Heavy Embroidered Net Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-68",
    slug: "embroidered-net-suit-with-silk-dupatta-net",
    sku: "LV-NT-68",
    name: "Embroidered Net Suit with Silk Dupatta",
    category: categories.net,
    priceMinor: 686400,
    currency: "PKR",
    blurb: "Net carrying embroidery carried across the front and daman, under a silk dupatta.",
    description: [
      "Net is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman.",
      "The dupatta is silk, set apart from the shirt cloth on purpose — a lighter hand than the suit itself, so it reads as a separate layer rather than more of the same.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Net" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Silk" },
      { label: "Work", value: "Embroidered" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-68", "LV-NT-68", 12),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752614914/Products/73/image/media_1752614410493_1752614914844.jpg", alt: "Embroidered Net Suit with Silk Dupatta", width: 504, height: 725 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752614914/Products/73/image/media_1752614410187_1752614913975.jpg", alt: "Embroidered Net Suit with Silk Dupatta, view 2", width: 904, height: 1280 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752614915/Products/73/image/media_1752614410808_1752614915427.jpg", alt: "Embroidered Net Suit with Silk Dupatta, view 3", width: 661, height: 800 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },
  {
    id: "lv-126",
    slug: "heavy-embroidered-net-suit-net",
    sku: "LV-NT-126",
    name: "Heavy Embroidered Net Suit",
    category: categories.net,
    priceMinor: 836600,
    currency: "PKR",
    blurb: "Net carrying embroidery carried across the front and daman, under a net dupatta.",
    description: [
      "Net is the ground here — cut for the shirt and trouser both, so the piece moves as one weight rather than two. The work is embroidery carried across the front and daman, with the heavier hand of formalwear rather than an everyday cut.",
      "The dupatta is net, set apart from the shirt cloth on purpose — a lighter hand than the suit itself, so it reads as a separate layer rather than more of the same.",
      "Unstitched, as every piece on this rail is — the shirt, trouser and dupatta arrive as cut cloth, and the fit is decided by whoever sews it, not by us.",
    ],
    specs: [
      { label: "Shirt", value: "Net" },
      { label: "Trouser", value: "Silk" },
      { label: "Dupatta", value: "Net" },
      { label: "Work", value: "Embroidered, Formal" },
      { label: "Care", value: "Hand Wash Only" },
    ],
    variants: unstitched("lv-126", "LV-NT-126", 4),
    images: [
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663595/Products/131/image/media_1752663275875_1752663595621.jpg", alt: "Heavy Embroidered Net Suit", width: 372, height: 432 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663596/Products/131/image/media_1752663276174_1752663596272.jpg", alt: "Heavy Embroidered Net Suit, view 2", width: 652, height: 800 },
      { url: "https://res.cloudinary.com/dhyz3jzmy/image/upload/v1752663597/Products/131/image/media_1752663276497_1752663596826.jpg", alt: "Heavy Embroidered Net Suit, view 3", width: 960, height: 1280 },
    ],
    visual: "ring",
    status: "active",
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2025-10-15T09:00:00.000Z",
  },

];
