import type { Metadata, Viewport } from "next";
import { fontVariables } from "@/lib/fonts";
import { siteDescription, siteName, siteUrl } from "@/lib/site";
import { SmoothScroll } from "@/components/providers/smooth-scroll";
import { MotionProvider } from "@/components/providers/motion-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { CartProvider } from "@/components/cart/cart-provider";
import { WhatsAppFloat } from "@/components/ui/whatsapp-float";
import { ScrollToTop } from "@/components/ui/scroll-to-top";
import { CartDrawer } from "@/components/cart/cart-drawer";
import { WishlistProvider } from "@/components/wishlist/wishlist-provider";
import { RecentlyViewedProvider } from "@/components/recently-viewed/recently-viewed-provider";
import "./globals.css";


export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    // Product and section pages supply the leading half; the wordmark trails it.
    default: "Levenon — Unstitched. Yours to finish.",
    template: "%s — Levenon",
  },
  description: siteDescription,
  applicationName: "Levenon",
  authors: [{ name: "Levenon" }],
  creator: "Levenon",
  publisher: "Levenon",
  keywords: [
    "tailored clothing",
    "small run clothing",
    "outerwear",
    "knitwear",
    "shirting",
    "Lahore",
  ],
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    siteName,
    locale: "en_PK",
    url: "/",
    title: "Levenon — Unstitched. Yours to finish.",
    description: siteDescription,
    // The image itself is generated by app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: "Levenon — Unstitched. Yours to finish.",
    description: siteDescription,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  category: "shopping",
  formatDetection: { telephone: false, address: false, email: false },
};

export const viewport: Viewport = {
  themeColor: "#FBFAF8",
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  /*
   * `suppressHydrationWarning` below is required by next-themes and is not a
   * way of hiding a bug: the theme script runs before React hydrates and writes
   * `data-theme` onto <html>, so server and client markup differ there by
   * design. The suppression is scoped to that one element.
   */
  return (
    <html lang="en" className={fontVariables} suppressHydrationWarning>
      <head>
        {/*
          Every product image is served straight from Cloudinary now (see
          lib/cloudinary-loader.ts), so the very first tile pays a DNS +
          TLS round trip to a third origin before a single byte arrives.
          Warming that connection during HTML parse takes it off the
          critical path — the standard fix whenever images live on a
          different origin from the document.
        */}
        <link rel="preconnect" href="https://res.cloudinary.com" crossOrigin="" />
        <link rel="dns-prefetch" href="https://res.cloudinary.com" />
      </head>
      <body className="bg-paper text-ink antialiased">
        <a
          href="#main"
          className="label sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-full focus:bg-ink focus:px-5 focus:py-3 focus:text-paper"
        >
          Skip to content
        </a>
        <SmoothScroll />
        {/* Outermost: every `m` element below needs the feature bundle. */}
        <ThemeProvider>
        <MotionProvider>
          {/* Separate providers: clearing one must never touch the other. */}
          <WishlistProvider>
            <RecentlyViewedProvider>
              <CartProvider>
                {children}
                <CartDrawer />
                {/*
                  Both read `useCart()` (WhatsAppFloat hides while the drawer
                  is open), so both have to sit inside CartProvider.
                */}
                <WhatsAppFloat />
                <ScrollToTop />
              </CartProvider>
            </RecentlyViewedProvider>
          </WishlistProvider>
        </MotionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
